// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyNbBImNz1hydWBIPDtOBPFZQb1dQGGZM',
    appId: '1:259872395645:web:7541f131a3c18e39b7bc14',
    messagingSenderId: '259872395645',
    projectId: 'to-do-app-792f0',
    authDomain: 'to-do-app-792f0.firebaseapp.com',
    storageBucket: 'to-do-app-792f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaPUXX54s-IBdais1mFyKsPwGiesjrq-8',
    appId: '1:259872395645:android:1706f3e1dcc2b174b7bc14',
    messagingSenderId: '259872395645',
    projectId: 'to-do-app-792f0',
    storageBucket: 'to-do-app-792f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyEHBXzJkDiKuzPa7rcegsT10oauEHqAc',
    appId: '1:259872395645:ios:cbcfb0f517a0b6b8b7bc14',
    messagingSenderId: '259872395645',
    projectId: 'to-do-app-792f0',
    storageBucket: 'to-do-app-792f0.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyEHBXzJkDiKuzPa7rcegsT10oauEHqAc',
    appId: '1:259872395645:ios:abf85d686b17bd3cb7bc14',
    messagingSenderId: '259872395645',
    projectId: 'to-do-app-792f0',
    storageBucket: 'to-do-app-792f0.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
